import Head from 'next/head'

const styles = {
  backgroundColor: '#000',
  color: '#eee',
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  height: '100vh',
  fontFamily: 'Arial, sans-serif'
}

const Home = () => {
  return (
    <>
      <Head>
        <title>BetterView</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={styles}>
        <h1>BetterView</h1>
      </main>
    </>
  )
}

export default Home
