import { MainLayout } from '@/components/layouts/MainLayout'
import Head from 'next/head'

const Home = () => {
  return (
    <>
      <Head>
        <title>BetterView</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div className='flex flex-col items-center justify-center gap-6 w-full h-full'>
          <h1 className='text-center font-extralight w-full'>
            Better<span className='font-extrabold'>View</span>
          </h1>
          <h2 className='text-center font-extralight w-[80%]'>Innovative Web Development for Modern Businesses</h2>
        </div>
      </MainLayout>
    </>
  )
}

export default Home
